### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by cyrus-shahrivar** [cyrus-shahrivar/refugeeDataViz#1]
- https://github.com/cyrus-shahrivar/refugeeDataViz/blob/dev/planning/final-project-proposal.md

@jasonseminara @WilliamfShaw @zhenpanda @amcooper

**Comment by jasonseminara** [comment]
Excellent! 

I think this is interesting, timely, and important. 

Focus on simply getting the data/scraping/viz part down, and then outline how the user interaction will play out.  

Approved. Close this if you agree.

**Comment by cyrus-shahrivar** [comment]
Thanks Jason!
